# Generated by Django 3.2.2 on 2021-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('symbol', models.CharField(default='', max_length=20)),
                ('open', models.DecimalField(decimal_places=8, max_digits=25)),
                ('high', models.DecimalField(decimal_places=8, max_digits=25)),
                ('low', models.DecimalField(decimal_places=8, max_digits=25)),
                ('close', models.DecimalField(decimal_places=8, max_digits=25)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=25)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
