# Generated by Django 3.2.2 on 2021-05-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='', max_length=255)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
