version: '3.1'

services:
  # Initialize a postgresql service
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testtest
    ports:
      - 5432:5432
  # Initialize an adminer service
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080